# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'Onstagram' do
use_frameworks!

# Pods for Onstagram
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'

end
